### ISSUE TITLE
Drop `discord.js` dependency

### ISSUE THREAD

**Issue by Wissididom** [Wissididom/Twitch-Discord-Clips-Webhook-Service#23]
Since this service runs continuesly and only checks for clips in the last few minutes I think I would be enough to just use fetch for posting the webhook message instead of bringing in all of `discord.js` just for a single POST request per clip.
I need to play around with how easy it is to implement tho, because I want to implement a little bit of rate limiting logic in that version too, then.

**Comment by bimoware** [comment]
For future reference for you and others interressted, here's the code for the POST request, btw using node-fetch since it's native and the main purpose of this change is to eliminate enormous & unuseful packages, but any would work.

```js
const fetch = require('node-fetch');

let params = {
    username: "Username",
    avatar_url: "URL", // I'm pretty sure this & username are optionnal but anyways
    content
}

fetch(process.env.DISCORD_WEBHOOK_URL, {
    method: "POST",
    headers: {
        'Content-type': 'application/json'
    },
    body: JSON.stringify(params)
}).then(res => {
  // ...
}) 
```
good luck 👍🏽

**Comment by Wissididom** [comment]
I don't see the request being difficult, I rather think, the more difficult part would be the rate limit handling. Since I use ES modules and don't plan on supporting versions older that Node 18 I don't think I'd need the require/import/node-fetch tho, because afaik since Node 18 fetch is a global that can be used without any import.

For the username and avatar, yes, that is optional, but I'm using it to impersonate the Twitch user so the clip creator looks like the author of the discord message.

**Comment by bimoware** [comment]
I'm sure the ratelimiting wouldn't be hard. From what I'm seeing, it's just checking the difference between the last sent request date & current date and
if too short, return an rate limit response
and if it's long enough, send the message and reset the "request date" being the current date.
And damn I didn't even notice being so used to node-fetch, thank god native fetch is mostly inspired by node-fetch

**Comment by Wissididom** [comment]
I don't return things here, I'd need to queue up the messages, because the script polls twitches API every few seconds and isn't called by a tool or so and I don't want clips to be missing in discord (as long as Twitch returns them all), but since it's 02:05am here, I won't be looking into it now and that's also why I try to answer without looking at the code.

**Comment by Wissididom** [comment]
Closing because considering #30 I'll probably still need it.
